#######################################-#######################################
##                                 CUSTOMIZE                                   
#######################################-#######################################
homeassistant:
  customize:
    ################################################
    ## NODE ANCHORS
    ################################################
    package.node_anchors:
      customize: &customize
        package: Centro Notifiche
        version: Google 2.6
        author: Caio & Gianpi
        site: www.hassiohelp.eu

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

  ## INPUT
    input_boolean.tts_google_mode:
      <<: *customize
      friendly_name: Google Say / Google Assistant
      icon: mdi:google
    input_boolean.google_switch:
      <<: *customize
      friendly_name: Google
      icon: mdi:google-home
    input_select.notification_media_player_google:
      <<: *customize
      friendly_name: Sorgente Google
      icon: mdi:speaker-wireless
  ## SENSOR
    sensor.media_player_google:
      <<: *customize
      friendly_name: 'Player Google Attivo'

#######################################-#######################################
##                                   INPUT
#######################################-#######################################
input_boolean:
  tts_google_mode:
  google_switch:
input_select:
  notification_media_player_google:
    options: !secret notification_media_player_google_hub

#######################################-#######################################
##                                  SENSOR
#######################################-#######################################
sensor:
  - platform: template
    sensors:
      media_player_google:
        value_template: >-
          {%set domains=['media_player','group']-%}
          {%for x in states if x.domain in domains and x.name|lower==states('input_select.notification_media_player_google')|lower-%}
          {%if x.domain=='group'%}{{-x.attributes.entity_id|join(', ')-}}{%else%}{{-x.entity_id-}}{%endif%}{%endfor%}
        icon_template: >-
          {%set domains=['media_player','group']-%}
          {%for x in states if x.domain in domains and x.name|lower==states('input_select.notification_media_player_google')|lower-%}
          {%if x.domain=='group'%}mdi:speaker-multiple{%else%}mdi:speaker{%endif%}{%endfor%}
