#######################################-#######################################
##                                  CONFIG                                   
#######################################-#######################################
homeassistant:
  customize:
    config:
      #----------------------------------------------------------------------------------------------------#
      # APP ARIELA TTS - Inserire MQTT Topic Trigger in ariela_tts_mqtt
      # Dal Menu/Impostazioni/Sensors/Text to Speech - attivare il sensore, selezionare MQTT 
      # copiare il codice premendo sui tre puntini veritcali.
      #----------------------------------------------------------------------------------------------------#
      ariela_tts_mqtt: homeassistant/tts/android_oneplus_5t_tts/tts
      tts_google: google_translate_say
      notify_google: google_assistant

group:
  #----------------------------------------------------------------------------------------------------#
  # Inserire i dispositivi da tracciare
  #----------------------------------------------------------------------------------------------------#
  location_tracker:
    name: Dispositivi tracciati
    entities:
      - person.claudio

input_select:
  #----------------------------------------------------------------------------------------------------#
  # Inserire i propri servizi di notifica   http://hassio:8123/dev-service nel campo servizio           
  #                                         digita notify. (con il punto) e vedrai quali sono i tuoi    
  #----------------------------------------------------------------------------------------------------#
  default_notify:
    name: Notifica Predefinita
    icon: mdi:message-settings-variant
    options:
      - Telegram
      - TelegramHTML
      - Pushover
      - Android
      - Pushbullet
      - Test Nome NOTIFICA
      - Mobile App Oneplus 5t

  #----------------------------------------------------------------------------------------------------#
  # Inserire i propri dispositivi GOOGLE con il proprio friandly_name o usare il file secret.yaml      #
  #----------------------------------------------------------------------------------------------------#
  notification_media_player_google:
    name: Sorgente Google
    icon: mdi:speaker-wireless
    options:
      - Red
      - Black
      - Black2
      - Gruppo Casa
      - Gruppo Google
      - Gruppo Google Notte

  #----------------------------------------------------------------------------------------------------#
  # Inserire i propri dispositivi ALEXA e/o GROUP con il proprio friandly_name.
  #----------------------------------------------------------------------------------------------------#
  notification_media_player_alexa:
    name: Sorgente Alexa
    icon: mdi:speaker-wireless
    options:
      - Sala
      - Studio
      - Gruppo Alexa
      - Last Alexa