#######################################-#######################################
##                                 CUSTOMIZE                                   
#######################################-#######################################
homeassistant:
  customize:
    ################################################
    ## NODE ANCHORS
    ################################################
    package.node_anchors:
      customize: &customize
        package: Centro Notifiche
        version: Ariela 2.0
        author: Caio & Gianpi
        site: www.hassiohelp.eu

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ## INPUT
    input_boolean.ariela_switch:
      <<: *customize
      friendly_name: Ariela
      icon: mdi:android-studio

    # input_boolean.ariela_push:
    #   <<: *customize
    #   friendly_name: Ariela Push
    #   icon: mdi:cellphone-text

#######################################-#######################################
##                                   INPUT
#######################################-#######################################
input_boolean:
  ariela_switch:
  # ariela_push:

