homeassistant:
  ######################################-#######################################
  ##                                CUSTOMIZE
  ######################################-#######################################
  customize:
    ## NODE ANCHORS
    package.node_anchors:
      customize: &customize
        package: "Centro Notifiche 🔔"
        site: "hassiohelp.eu 🌐"
        author: "Caio & Gianpi"
        version: "Google 4.0.0"

    ## INPUT
    input_boolean.notifier_google_switch:
      <<: *customize
      friendly_name: "Google Off/On"
      icon: mdi:dots-horizontal-circle-outline
    input_select.notifier_tts_notify:
      <<: *customize
      friendly_name: "Servizio TTS"
      icon: mdi:form-select
    input_text.notifier_player_google:
      <<: *customize
      friendly_name: "Nome Media Player Google Salvato"
      icon: mdi:multimedia
    ## SELECT
    select.notifier_player_google:
      <<: *customize
      friendly_name: "Sorgente Google"
      icon: mdi:speaker-wireless
    ## SENSOR
    sensor.notifier_player_google:
      <<: *customize
      friendly_name: "Player Google Predefinito"

#######################################-#######################################
##                                   INPUT
#######################################-#######################################
input_boolean:
  notifier_google_switch:
input_select:
  notifier_tts_notify:
    options: ["Google Say", "Google Cloud", "Google Assistant", "Reverso"]
input_text:
  notifier_player_google:
#######################################-#######################################
##                                 TEMPLATE
#######################################-#######################################
template:
  - select:
      - name: "notifier_player_google"
        state: "{{ states('input_text.notifier_player_google') }}"
        optimistic: true
        options: |
          {% set mp = state_attr('group.notifier_player_google', 'entity_id')
            | default(['\0'], true) | join('|') %}
          {{ states | select('search', mp, ignorecase=True)
            | rejectattr('entity_id', '==','sensor.notifier_player_google')
            | map(attribute='name') | list | unique | sort }}
        select_option:
          - service: input_text.set_value
            target:
              entity_id: input_text.notifier_player_google
            data:
              value: "{{ option }}"

  - trigger:
      - platform: state
        entity_id:
          - select.notifier_player_google
          - input_text.notifier_player_google
      - platform: state
        entity_id: group.notifier_player_google
        attribute: entity_id
      - platform: state
        entity_id: sensor.notifier_player_google
        to: unknown
    sensor:
      - name: "notifier_player_google"
        state: >-
          {% set domains = (states.group | list) + (states.media_player | list) %}
          {% set player = state_attr('group.notifier_player_google','entity_id') %}          
          {% set selected = states('select.notifier_player_google') | lower %}
          {% for x in domains if x.name | lower == selected %}
            {% if x.domain == 'group' and player 
                and x.attributes.entity_id[0] in player | list %}
              {{ x.attributes.entity_id | join(', ') }}
            {% elif x.domain == 'media_player' %}
              {{ x.entity_id }}
            {% else %}
              {{ (player | join(', ')) if player else 'all' }}
            {% endif %}
          {% endfor %}
        icon: >-
          {{ iif(',' in this.state | default('', true), 
              'mdi:speaker-multiple', 'mdi:speaker') }}
        attributes:
          saved: "{{ states('input_text.notifier_player_google') }}"
