#######################################-#######################################
##                                 CUSTOMIZE                                   
#######################################-#######################################
homeassistant:
  customize:
    ################################################
    ## NODE ANCHORS
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'Centro Notifiche'
        version: 'Ariela 2.0'
        author: 'Caio & Gianpi'
        site: 'www.hassiohelp.eu'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## input Boolean
    ################################################
    input_boolean.ariela_switch:
      <<: *customize
    # input_boolean.ariela_push:
    #   <<: *customize

#######################################-#######################################
##                                   INPUT
#######################################-#######################################

input_boolean:
  ariela_switch:
    name: Ariela
    icon: mdi:android-studio

  # ariela_push:
  #   name: Ariela Push
  #   icon: mdi:cellphone-text
