# package_hub_google:
homeassistant:
  ######################################-#######################################
  ##                                CUSTOMIZE
  ######################################-#######################################
  customize:
    ## NODE ANCHORS
    package.node_anchors:
      customize: &customize
        package: "Centro Notifiche 🔔"
        site: "hassiohelp.eu 🌐"
        author: "Caio & Gianpi"
        version: "Google 3.3.2"

    ## INPUT
    input_boolean.google_switch:
      <<: *customize
      friendly_name: "Google"
      icon: mdi:google-home
    input_select.tts_notify:
      <<: *customize
      friendly_name: "Servizio TTS"
      icon: mdi:form-select
    input_select.notification_media_player_google:
      <<: *customize
      friendly_name: "Sorgente Google"
      icon: mdi:speaker-wireless
    ## SENSOR
    sensor.media_player_google:
      <<: *customize
      friendly_name: "Player Google Attivo"

#######################################-#######################################
##                                   INPUT
#######################################-#######################################
input_boolean:
  google_switch:

input_select:
  tts_notify:
    options: ["Google Say", "Google Cloud", "Google Assistant", "Reverso"]
  notification_media_player_google:
    options: !secret notification_media_player_google_hub

#######################################-#######################################
##                                 TEMPLATE
#######################################-#######################################
template:
  - trigger:
      - platform: state
        entity_id: input_select.notification_media_player_google
        to:
      - platform: state
        entity_id: group.media_player_google
        attribute: entity_id
      # - platform: event
      #   event_type: event_template_reloaded
      - platform: state
        entity_id: sensor.media_player_google
        to: unknown
    sensor:
      - name: Media Player Google
        unique_id: media_player_google
        state: >-
          {% set domains = states.group | list + states.media_player | list %}
          {% set selected = states('input_select.notification_media_player_google') | lower %}
          {% for x in domains if x.name | lower == selected %}
            {% if x.domain == 'group' %}
              {{ x.attributes.entity_id | join(', ') }}
            {% else %}
              {{ x.entity_id }}
            {% endif %}
          {% endfor %}
        icon: >-
          {% set domains = states.group | list + states.media_player | list %}
          {% set selected = states('input_select.notification_media_player_google') | lower %}
          {% for x in domains if x.name | lower == selected %}
            {% if x.domain == 'group'%}
              mdi:speaker-multiple
            {%elif x.domain == 'sensor' %}
              mdi:cast-audio
            {% else %}
              mdi:speaker
            {% endif %}
          {% endfor %}
