#######################################-#######################################
##                                 CUSTOMIZE
#######################################-#######################################
homeassistant:
  customize:
    ## NODE ANCHORS
    package.node_anchors:
      customize: &customize
        package: Centro Notifiche 🔔
        site: hassiohelp.eu 🌐
        author: Caio & Gianpi
        version: Alexa 3.2.0

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ## INPUT
    input_boolean.alexa_switch:
      <<: *customize
      friendly_name: Alexa
      icon: mdi:amazon-alexa
    input_boolean.alexa_ssml:
      <<: *customize
      friendly_name: Auto SSML
      icon: mdi:waveform
    input_number.alexa_prosody_rate:
      <<: *customize
      friendly_name: Rate
      icon: mdi:alpha-r
    input_number.alexa_prosody_pitch:
      <<: *customize
      friendly_name: Pitch
      icon: mdi:alpha-p
    input_number.alexa_prosody_volume:
      <<: *customize
      friendly_name: Volume
      icon: mdi:alpha-v
      unit_of_measurement: "dB"
    input_select.alexa_voice:
      <<: *customize
      friendly_name: Amazon Polly voice
      icon: mdi:account-tie-voice-outline
    # input_select.alexa_language:
    #   <<: *customize
    #   friendly_name: Amazon Polly language
    #   icon: mdi:flag-variant
    input_select.notification_media_player_alexa:
      <<: *customize
      friendly_name: Sorgente Alexa
      icon: mdi:speaker-wireless
    input_select.default_alexa_method:
      <<: *customize
      friendly_name: Metodo Predefinito Alexa
      icon: mdi:monitor-speaker
    input_select.default_alexa_type:
      <<: *customize
      friendly_name: Tipo Predefinito Alexa
      icon: mdi:bugle
    ## SCRIPT
    script.ssml_reset:
      <<: *customize
      friendly_name: Ripristina SSML
      icon: mdi:restore
    ## SENSOR
    sensor.last_alexa:
      <<: *customize
      friendly_name: Last Alexa
      icon: mdi:play-network
    sensor.media_player_alexa:
      <<: *customize
      friendly_name: Player Alexa Attivo

#######################################-#######################################
##                                   INPUT
#######################################-#######################################
input_boolean:
  alexa_switch:
  alexa_ssml:
input_number:
  alexa_prosody_rate:
    min: 20
    max: 200
    step: 0.1
  alexa_prosody_pitch:
    min: -33.3
    max: 50
    step: 0.1
  alexa_prosody_volume:
    min: -50
    max: 4.08
    step: 0.01

input_select:
  notification_media_player_alexa:
    options: !secret notification_media_player_alexa_hub
  default_alexa_method:
    options:
      - Speak
      - All
  default_alexa_type:
    options:
      - TTS
      - Announce
      - Push
      - Dropin
  alexa_voice:
    options:
      [
        "Alexa",
        "Carla",
        "Giorgio",
        "Bianca",
        "Ivy",
        "Joanna",
        "Joey",
        "Justin",
        "Kendra",
        "Kimberly",
        "Matthew",
        "Salli",
        "Nicole",
        "Russell",
        "Amy",
        "Brian",
        "Emma",
        "Aditi",
        "Raveena",
        "Chantal",
        "Celine",
        "Lea",
        "Mathieu",
        "Hans",
        "Marlene",
        "Vicki",
        "Aditi",
        "Mizuki",
        "Takumi",
        "Vitoria",
        "Camila",
        "Ricardo",
        "Penelope",
        "Lupe",
        "Miguel",
        "Conchita",
        "Enrique",
        "Lucia",
        "Mia",
      ]

  # alexa_language:
  #   options: [
  #     "Master",
  #     "it-IT",
  #     "en-US", "en-CA",
  #     "en-AU",
  #     "en-GB",
  #     "en-IN",
  #     "fr-CA",
  #     "fr-FR",
  #     "de-DE",
  #     "hi-IN",
  #     "ja-JP",
  #     "pt-BR",
  #     "es-US",
  #     "es-ES",
  #     "es-MX",
  #     ]

#######################################-#######################################
##                                  SENSOR
#######################################-#######################################
sensor:
  - platform: template
    sensors:
      media_player_alexa:
        value_template: >
          {%set domains=['media_player','group','sensor']-%}
          {%for x in states if x.domain in domains and x.name|lower==states('input_select.notification_media_player_alexa')|lower-%}
          {%if x.domain=='sensor'%}{{x.state}}{%else%}{{-x.entity_id-}}{%endif%}{%endfor%}
        icon_template: >-
          {%set domains=['media_player','group','sensor']-%}
          {%for x in states if x.domain in domains and x.name|lower==states('input_select.notification_media_player_alexa')|lower-%}
          {%if x.domain=='group'%}mdi:speaker-multiple{%elif x.domain=='sensor'%}mdi:cast-audio{%else%}mdi:speaker{%endif%}{%endfor%}

#######################################-#######################################
##                                  SCRIPT
#######################################-#######################################
script:
  ssml_reset:
    sequence:
      - service: input_number.set_value
        data:
          entity_id: input_number.alexa_prosody_pitch, input_number.alexa_prosody_volume
          value: 0
      - service: input_number.set_value
        data:
          entity_id: input_number.alexa_prosody_rate
          value: 100
      - service: input_select.select_option
        data:
          entity_id: input_select.alexa_voice
          option: Alexa
      # - service: input_select.select_option
      #   data:
      #     entity_id: input_select.alexa_language
      #     option: it-IT
