### INFO
#   @author         :   Caio & Gianpi - hassiohelp.eu
#   @date           :   Started 01/11/2019 - Updated 07/11/2020
#   @package        :   Notification HUB - Centro Notifiche
#   @description    :   Package Appdaemon Notifier Center for Home Assistant
############################################################################

#######################################-#######################################
##                                 CUSTOMIZE
#######################################-#######################################
homeassistant:
  customize:
    ## NODE ANCHORS
    package.node_anchors:
      customize: &customize
        package: Centro Notifiche 🔔
        site: hassiohelp.eu 🌐
        author: Caio & Gianpi
        version: Main 3.0.2

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ## AUTOMATION
    automation.guest_mode_hub:
      <<: *customize
      friendly_name: Modo Ospite
    automation.notification_repeat_last_message_hub:
      <<: *customize
      friendly_name: Ripete Ultimo Messaggio
    automation.send_intercom_message_hub:
      <<: *customize
      friendly_name: Invia Messaggio Con Iterfono
      icon: mdi:bullhorn
    ## BINARY SENSOR
    binary_sensor.dnd:
      <<: *customize
      friendly_name: Modo Silenzioso
    ## GROUP
    group.automations_notification_hub:
      <<: *customize
      friendly_name: Automazioni HUB
      icon: mdi:account-tie
    group.location_tracker:
      <<: *customize
      friendly_name: Dispositivi tracciati
      icon: mdi:target-account
    ## INPUT BOOLEAN
    input_boolean.guest_mode:
      <<: *customize
      friendly_name: Modo Ospite
      icon: mdi:account-multiple-plus
    input_boolean.holidays:
      <<: *customize
      friendly_name: Modo Vacanza
      icon: mdi:beach
    input_boolean.html_mode:
      <<: *customize
      friendly_name: "Modo Markdown/Html"
      icon: mdi:language-html5 #language-markdown
    input_boolean.last_message:
      <<: *customize
      friendly_name: Ultimo Messaggio
      icon: mdi:repeat-once
    input_boolean.phone_notifications:
      <<: *customize
      friendly_name: Notifiche VoIP
      icon: mdi:phone-in-talk
    input_boolean.priority_message:
      <<: *customize
      friendly_name: Modo Prioritario
      icon: mdi:alarm-light
    input_boolean.screen_notifications:
      <<: *customize
      friendly_name: Notifiche Persistenti
      icon: mdi:message-bulleted
    input_boolean.speech_notifications:
      <<: *customize
      friendly_name: Notifiche Vocali
      icon: mdi:account-tie-voice
    input_boolean.text_notifications:
      <<: *customize
      friendly_name: Notifiche Testo
      icon: mdi:cellphone-message
    ## INPUT DATETIME
    input_datetime.start_morning:
      <<: *customize
      friendly_name: Mattina
      icon: mdi:timetable
    input_datetime.start_afternoon:
      <<: *customize
      friendly_name: Pomeriggio
      icon: mdi:timetable
    input_datetime.start_evening:
      <<: *customize
      friendly_name: Sera
      icon: mdi:timetable
    input_datetime.start_night:
      <<: *customize
      friendly_name: Notte
      icon: mdi:timetable
    ## INPUT NUMBER
    input_number.morning_volume:
      <<: *customize
      friendly_name: Vol Mattina
      icon: mdi:volume-medium
    input_number.afternoon_volume:
      <<: *customize
      friendly_name: Vol Pomeriggio
      icon: mdi:volume-high
    input_number.evening_volume:
      <<: *customize
      friendly_name: Vol Sera
      icon: mdi:volume-medium
    input_number.night_volume:
      <<: *customize
      friendly_name: Vol Notte
      icon: mdi:volume-low
    input_number.default_restore_volume:
      <<: *customize
      friendly_name: Volume Rispristino
      icon: mdi:volume-source
    input_number.intercom_message_volume:
      <<: *customize
      friendly_name: Volume
      icon: mdi:volume-source
    input_number.tts_wait_time:
      <<: *customize
      friendly_name: Regolazione attesa TTS
      icon: mdi:av-timer
      unit_of_measurement: "sec"
    ## INPUT SELECT
    input_select.language:
      <<: *customize
      friendly_name: Lingua
      icon: mdi:flag-variant
    input_select.phone_notify:
      <<: *customize
      friendly_name: Notifica Telefonica
      icon: mdi:phone-forward
    input_select.text_notify:
      <<: *customize
      friendly_name: Notifica Testo
      icon: mdi:message-cog
    ## INPUT TEXT
    input_text.phone_called_number:
      <<: *customize
      friendly_name: N. Tel / @user
      icon: mdi:phone-classic
    input_text.last_message:
      <<: *customize
      friendly_name: Salva Ultimo Messaggio
      icon: mdi:repeat
    input_text.intercom_message_hub:
      <<: *customize
      friendly_name: Messaggio
      icon: mdi:bullhorn-outline
    input_text.personal_assistant_name:
      <<: *customize
      friendly_name: Nome Assistente
    ## SCRIPT
    script.my_notify:
      <<: *customize
      friendly_name: HUB
    ## SENSOR
    sensor.centro_notifiche:
      <<: *customize
      friendly_name: Centro Notifiche
      icon: mdi:account-tie-outline
    sensor.period_of_day:
      <<: *customize
      friendly_name: Periodo del Giorno
    sensor.period_of_day_volume:
      <<: *customize
      friendly_name: Volume Notifica

  ############################################################################
  ##                             CUSTOMIZE GLOB
  ############################################################################
  customize_glob:
    automation.*_hub:
      <<: *customize
      icon: mdi:alpha-a-circle-outline
    input_datetime.dnd_start_*:
      <<: *customize
      friendly_name: Non disturbare inizio
      icon: mdi:clock-start
    input_datetime.dnd_end_*:
      <<: *customize
      friendly_name: Non disturbare fine
      icon: mdi:clock-end
    input_number.*_volume:
      <<: *customize
      unit_of_measurement: "%"
    sensor.*_volume:
      <<: *customize
      unit_of_measurement: "%"

###############################################################################
## PACKAGE
###############################################################################

###############################################################################
## OTHER COMPONENTS
###############################################################################
media_extractor:

#######################################-#######################################
##                                   GROUP
#######################################-#######################################
group:
  location_tracker:
    entities: !secret location_tracker_hub

#######################################-#######################################
##                                   INPUT
#######################################-#######################################
input_boolean:
  guest_mode:
  holidays:
  html_mode:
  last_message:
  phone_notifications:
  priority_message:
  screen_notifications:
  speech_notifications:
  text_notifications:
input_datetime:
  dnd_start_weekdays:
    has_date: false
    has_time: true
  dnd_end_weekdays:
    has_date: false
    has_time: true
  dnd_start_holidays:
    has_date: false
    has_time: true
  dnd_end_holidays:
    has_date: false
    has_time: true
  start_morning:
    has_date: false
    has_time: true
  start_afternoon:
    has_date: false
    has_time: true
  start_evening:
    has_date: false
    has_time: true
  start_night:
    has_date: false
    has_time: true
input_number:
  morning_volume:
    min: 0
    max: 100
    step: 10
  afternoon_volume:
    min: 0
    max: 100
    step: 10
  evening_volume:
    min: 0
    max: 100
    step: 10
  night_volume:
    min: 0
    max: 100
    step: 10
  intercom_message_volume:
    min: 0
    max: 100
    step: 10
  default_restore_volume:
    min: 0
    max: 100
    step: 10
  tts_wait_time:
    min: 0
    max: 5
    step: 0.1
input_select:
  text_notify:
    options: !secret text_notify_hub
  phone_notify:
    options: ["Telegram Call", "Voip Call"]
  language: # Uncomment if you want Extra language for Alexa
    options:
      ["it-IT", "en-GB", "en-US", "fr-FR", "de-DE", "es-ES", "ja-JP"]
      # "en-CA",
      # "en-AU",
      # "en-IN",
      # "fr-CA",
      # "hi-IN",
      # "ja-JP",
      # "pt-BR",
      # "es-US",
      # "es-MX",
input_text:
  last_message:
    max: 255
  intercom_message_hub:
    max: 255
    initial: ""
  personal_assistant_name:
    max: 255
  phone_called_number:
    max: 30
    mode: password

#######################################-#######################################
##                               BINARY SENSOR
#######################################-#######################################
binary_sensor:
  - platform: template
    sensors:
      dnd:
        value_template: >
          {%set speech=states('input_boolean.speech_notifications')%}
          {%set priority=states('input_boolean.priority_message')%}
          {%set t=now().time()%}
          {%set t=(t.hour*60+t.minute)*60+60%}
          {% set day = 'weekdays' if (is_state('binary_sensor.workday_sensor','on')
            and is_state('input_boolean.holidays','off')) else 'holidays' %}
          {%set start=state_attr('input_datetime.dnd_start_%s'%day,'timestamp')%}
          {%set stop=state_attr('input_datetime.dnd_end_%s'%day,'timestamp')%}
          {%if speech=='on' and priority=='off'%} 
          {{(start<t<stop) if start<stop else ((t>start or t<stop) and start != stop)}}
          {%elif speech=='off' and priority=='off'%}True{%else%}False{%endif%}
        icon_template: >
          {%if is_state('binary_sensor.dnd','off')%}mdi:do-not-disturb-off{%else%}mdi:do-not-disturb{%endif%}

#######################################-#######################################
##                                  SENSOR
#######################################-#######################################
sensor:
  - platform: template
    sensors:
      period_of_day:
        value_template: >
          {%set nt=now().time()%}
          {%set nt=(nt.hour*60+nt.minute)*60+nt.second%}
          {%if state_attr('input_datetime.start_morning','timestamp')<=nt<state_attr('input_datetime.start_afternoon','timestamp')%}Mattino
          {%elif state_attr('input_datetime.start_afternoon','timestamp')<=nt<state_attr('input_datetime.start_evening','timestamp')%}Pomeriggio
          {%elif state_attr('input_datetime.start_evening','timestamp')<=nt<state_attr('input_datetime.start_night','timestamp')%}Sera
          {%elif (state_attr('input_datetime.start_evening','timestamp')>state_attr('input_datetime.start_night','timestamp'))
          and (nt>state_attr('input_datetime.start_evening','timestamp') or nt<state_attr('input_datetime.start_night', 'timestamp'))%}Sera
          {%else%}Notte{%endif%}
        icon_template: >
          {%if is_state('sensor.period_of_day','Mattino')%}mdi:weather-sunset-up
          {%elif is_state('sensor.period_of_day','Pomeriggio')%}mdi:weather-sunny
          {%elif is_state('sensor.period_of_day','Sera') %}mdi:weather-sunset-down
          {%else%} mdi:weather-night{%endif%}
      period_of_day_volume:
        value_template: >
          {%if is_state('sensor.period_of_day','Mattino') %}{{states('input_number.morning_volume')|int}}
          {%elif is_state('sensor.period_of_day','Pomeriggio')%}{{states('input_number.afternoon_volume')|int}}
          {%elif is_state('sensor.period_of_day','Sera') %}{{states('input_number.evening_volume')|int}}
          {%else%}{{states('input_number.night_volume')|int}}{%endif%}
        icon_template: >
          {%if is_state('sensor.period_of_day_volume','0')%}mdi:volume-off
          {%elif is_state('sensor.period_of_day_volume','10')%}mdi:volume-low
          {%elif is_state('sensor.period_of_day_volume','20')%}mdi:volume-low
          {%elif is_state('sensor.period_of_day_volume','30')%}mdi:volume-low
          {%elif is_state('sensor.period_of_day_volume','40')%}mdi:volume-medium
          {%elif is_state('sensor.period_of_day_volume','50')%}mdi:volume-medium
          {%elif is_state('sensor.period_of_day_volume','60')%}mdi:volume-medium
          {%else%}mdi:volume-high{%endif%}
        attribute_templates:
          vol: >
            {%if is_state('sensor.period_of_day','Mattino') %}{{(states('input_number.morning_volume')|float)/100}}
            {%elif is_state('sensor.period_of_day','Pomeriggio')%}{{(states('input_number.afternoon_volume')|float)/100}}
            {%elif is_state('sensor.period_of_day','Sera') %}{{(states('input_number.evening_volume')|float)/100}}
            {%else%}{{(states('input_number.night_volume')|float)/100}}{%endif%}

#######################################-#######################################
##                                  SCRIPT
#######################################-#######################################
script:
  #----------------------------------------------------------------------------------------------------#
  # MAIN SCRIPT - Variables to be passed to the HUB + template file event if included
  #----------------------------------------------------------------------------------------------------#
  my_notify:
    alias: HUB
    mode: queued
    sequence:
      - event: hub
        event_data:
          # --------------------------------------------- #
          # VARIABLES
          # --------------------------------------------- #
          alexa: >-
            {{alexa}}
          called_number: >-
            {{called_number}}
          caption: >-
            {{caption}}
          file: >-
            {{file}}
          google: >-
            {{google}}
          html: >-
            {{html}}
          link: >-
            {{link}}
          location: >-
            {{location}}
          no_show: >-
            {{no_show}}
          notify: >-
            {{notify}}
          priority: >-
            {{priority}}
          title: >-
            {{title}}
          url: >-
            {{url}}
          #-------------------------------------------------------------------------------#
          # FILE TO BE INCLUDED IF MACROS ARE USED - NOTE: DO NOT MODIFY THE .yml EXTENSION
          #-------------------------------------------------------------------------------#
          message: !include hub_build_message.yml

#######################################-#######################################
##                               SHELL COMMAND
#######################################-#######################################
# https://www.callmebot.com/blog/telegram-call-from-home-assistant/
shell_command:
  telegram_call: "/usr/bin/wget {{url}} -O /dev/null"
  #telegram_call: '/usr/bin/curl {{url}} -O /dev/null' # alternative

#######################################-#######################################
##                                 AUTOMATION
#######################################-#######################################
automation:
  #----------------------------------------------------------------------------------------------------#
  # LAST MESSAGE - Repeat the last text sent (Excluding tts messages)
  #----------------------------------------------------------------------------------------------------#
  - alias: Notification Repeat Last Message Hub
    initial_state: true
    mode: queued
    trigger:
      - platform: state
        entity_id: input_boolean.last_message
        to: "on"
    action:
      # - service: input_boolean.turn_on
      #   data:
      #     entity_id: input_boolean.priority_message
      - service: script.my_notify
        data:
          title: "Ultimo messaggio"
          message: >
            {{states('input_text.last_message')}}
          <<: &common
            call_no_annuncio: true
            alexa:
              volume: &intercom_volume >
                {{states('input_number.intercom_message_volume')|int/100}}
            google:
              volume: *intercom_volume
      - service: input_boolean.turn_off
        entity_id:
          # - input_boolean.priority_message
          - input_boolean.last_message
  #----------------------------------------------------------------------------------------------------#
  # INTERCOM - To send messages from the GUI (graphical user interface)
  #----------------------------------------------------------------------------------------------------#
  - alias: Send Intercom Message Hub
    initial_state: true
    mode: queued
    trigger:
      - platform: state
        entity_id: input_text.intercom_message_hub
    condition: "{{states('input_text.intercom_message_hub')|trim != ''}}"
    action:
      - service: script.my_notify
        data:
          title: "Interfono"
          message: >
            {{states('input_text.intercom_message_hub')~' '}}
          <<: *common
      - service: input_text.set_value
        data:
          entity_id: input_text.intercom_message_hub
          value: ""
  #----------------------------------------------------------------------------------------------------#
  # GUEST - On and Off guest mode - The TTS works even if you are away from home.
  #         Useful even if you want to exclude automations if there are guests in the house
  #----------------------------------------------------------------------------------------------------#
  - alias: Guest Mode Hub
    initial_state: true
    mode: queued
    trigger:
      platform: state
      entity_id: input_boolean.guest_mode
    action:
      - service: script.my_notify
        data:
          title: >
            Modalità Ospite - {{trigger.to_state.state|upper}}
          call_no_annuncio: true
          call_modo_ospite: true
          alexa: true
          google: true
