### INFO
  #   @author         :   Caio & Gianpi- www.hassiohelp.eu
  #   @date           :   Started 01/11/2019 - Updated 08/01/2020
  #   @package        :   Notification HUB - Centro Notifiche
  #   @description    :   Package Appdaemon Notifier Center for Home Assistant
  ############################################################################

#######################################-#######################################
##                                 CUSTOMIZE                                   
#######################################-#######################################
homeassistant:
  customize:
  ## NODE ANCHORS
    package.node_anchors:
      customize: &customize
        package: Centro Notifiche
        version: Main 2.3
        author: Caio & Gianpi
        site: www.hassiohelp.eu
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

  ## AUTOMATION
    automation.create_notification_automation_group_hub:
      <<: *customize
      friendly_name: Crea Gruppo Automazioni HUB
    automation.guest_mode_hub:
      <<: *customize
      friendly_name: Modo Ospite
    automation.notification_repeat_last_message_hub:
      <<: *customize
      friendly_name: Ripete Ultimo Messaggio
    automation.send_intercom_message_hub:
      <<: *customize
      friendly_name: Invia Messaggio Con Iterfono
      icon: mdi:bullhorn
  ## BINARY SENSOR
    binary_sensor.dnd:
      <<: *customize
      friendly_name: Modo Silenzioso
  ## GROUP
    group.automations_notification_hub:
      <<: *customize
      friendly_name: Automazioni HUB
      icon: mdi:account-tie
    group.location_tracker:
      <<: *customize
      friendly_name: Dispositivi tracciati
      icon: mdi:target-account
  ## INPUT BOOLEAN
    input_boolean.guest_mode:
      <<: *customize
      friendly_name: Modo Ospite
      icon: mdi:account-multiple-plus
    input_boolean.holidays:
      <<: *customize
      friendly_name: Modo Vacanza
      icon: mdi:beach
    input_boolean.last_message:
      <<: *customize
      friendly_name: Ultimo Messaggio
      icon: mdi:repeat-once
    input_boolean.phone_notifications:
      <<: *customize
      friendly_name: Notifiche VoIP
      icon: mdi:phone-in-talk
    input_boolean.priority_message:
      <<: *customize
      friendly_name: Modo Prioritario
      icon: mdi:alarm-light
    input_boolean.screen_notifications:
      <<: *customize
      friendly_name: Notifiche Persistenti
      icon: mdi:message-bulleted
    input_boolean.speech_notifications:
      <<: *customize
      friendly_name: Notifiche Vocali
      icon: mdi:voice
    input_boolean.text_notifications:
      <<: *customize
      friendly_name: Notifiche Testo
      icon: mdi:cellphone-message
  ## INPUT DATETIME
    input_datetime.start_morning:
      <<: *customize
      friendly_name: Mattina
      icon: mdi:timetable
    input_datetime.start_afternoon:
      <<: *customize
      friendly_name: Pomeriggio
      icon: mdi:timetable
    input_datetime.start_evening:
      <<: *customize
      friendly_name: Sera
      icon: mdi:timetable
    input_datetime.start_night:
      <<: *customize
      friendly_name: Notte
      icon: mdi:timetable
  ## INPUT NUMBER
    input_number.morning_volume:
      <<: *customize
      friendly_name: Vol Mattina
      icon: mdi:volume-medium
    input_number.afternoon_volume:
      <<: *customize
      friendly_name: Vol Pomeriggio
      icon: mdi:volume-high
    input_number.evening_volume:
      <<: *customize
      friendly_name: Vol Sera
      icon: mdi:volume-medium
    input_number.night_volume:
      <<: *customize
      friendly_name: Vol Notte
      icon: mdi:volume-low
    input_number.default_restore_volume:
      <<: *customize
      friendly_name: Volume Rispristino
      icon: mdi:volume-source
    input_number.intercom_message_volume:
      <<: *customize
      friendly_name: Volume
      icon: mdi:volume-source
    input_number.tts_wait_time:
      <<: *customize
      friendly_name: Regolazione attesa TTS
      icon: mdi:av-timer
  ## INPUT SELECT
    input_select.phone_notify:
      <<: *customize
      friendly_name: Notifica Telefonica
      icon: mdi:phone-forward
    input_select.text_notify:
      <<: *customize
      friendly_name: Notifica Testo
      icon: mdi:message-settings-variant
    input_text.phone_called_number:
      <<: *customize
      friendly_name: N. Tel / @user
      icon: mdi:phone-classic
  ## INPUT TEXT
    input_text.last_message:
      <<: *customize
      friendly_name: Salva Ultimo Messaggio
      icon: mdi:repeat
    input_text.intercom_message_hub:
      <<: *customize
      friendly_name: Messaggio
      icon: mdi:bullhorn
    input_text.personal_assistant_name:
      <<: *customize
      friendly_name: Nome Assistente
  ## SCRIPT
    script.my_notify:
      <<: *customize
      friendly_name: HUB
  ## SENSOR
    sensor.period_of_day:
      <<: *customize
      friendly_name: Periodo del Giorno
    sensor.period_of_day_volume:
      <<: *customize
      friendly_name: Volume Notifica
############################################################################
##                             CUSTOMIZE GLOB                              
############################################################################
  customize_glob:
    automation.*_hub:
      <<: *customize
      icon: mdi:alpha-a-circle-outline
    input_datetime.dnd_start_*:
      <<: *customize
      friendly_name: Non disturbare inizio
      icon: mdi:clock-start
    input_datetime.dnd_end_*:
      <<: *customize
      friendly_name: Non disturbare fine
      icon: mdi:clock-end
###############################################################################
## PACKAGE
###############################################################################

#######################################-#######################################
##                                   GROUP
#######################################-#######################################
group:
  location_tracker:
    entities: !secret location_tracker_hub

#######################################-#######################################
##                                   INPUT
#######################################-#######################################
input_boolean:
  guest_mode:
  holidays:
  last_message:
  phone_notifications:
  priority_message:
  screen_notifications:
  speech_notifications:
  text_notifications:
input_datetime:
  dnd_start_weekdays:
    has_date: false
    has_time: true
  dnd_end_weekdays:
    has_date: false
    has_time: true
  dnd_start_holidays:
    has_date: false
    has_time: true
  dnd_end_holidays:
    has_date: false
    has_time: true
  start_morning:
    has_date: false
    has_time: true
  start_afternoon:
    has_date: false
    has_time: true
  start_evening:
    has_date: false
    has_time: true
  start_night:
    has_date: false
    has_time: true
input_number:
  morning_volume:
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
  afternoon_volume:
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
  evening_volume:
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
  night_volume:
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
  intercom_message_volume:
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
  default_restore_volume:
    min: 0
    max: 100
    step: 10
    unit_of_measurement: '%'
  tts_wait_time:
    min: 0
    max: 5
    step: 0.1
    unit_of_measurement: 'sec'
input_select:
  text_notify:
    options: !secret text_notify_hub
  phone_notify:
    options: !secret phone_notify_hub
input_text:
  last_message:
    max: 255
  intercom_message_hub:
    max: 255
    initial: ''
  personal_assistant_name:
    max: 255
  phone_called_number:
    max: 30
    initial: ''
#######################################-#######################################
##                               BINARY SENSOR
#######################################-#######################################
binary_sensor:
  - platform: template
    sensors:
      dnd:
        entity_id: >
          sensor.time,input_datetime.dnd_start_weekdays,input_datetime.dnd_end_weekdays,
          input_datetime.dnd_start_holidays,input_datetime.dnd_end_holidays,
          input_boolean.speech_notifications,input_boolean.priority_message,input_boolean.holidays
        value_template: >
          {%set speech=states('input_boolean.speech_notifications')%}
          {%set priority=states('input_boolean.priority_message')%}
          {%set t=now().time()%}
          {%set t=(t.hour*60+t.minute)*60+t.second%}
          {% set day = 'weekdays' if (is_state('binary_sensor.workday_sensor','on')
            and is_state('input_boolean.holidays','off')) else 'holidays' %}
          {%set start=state_attr('input_datetime.dnd_start_%s'%day,'timestamp')%}
          {%set stop=state_attr('input_datetime.dnd_end_%s'%day,'timestamp')%}
          {%if speech=='on' and priority=='off'%} 
          {{(start<t<stop) if start<stop else (t>start or t<stop)}}
          {%elif speech=='off' and priority=='off'%}True{%else%}False{%endif%}
        icon_template: >
          {%if is_state('binary_sensor.dnd','off')%}mdi:do-not-disturb-off{%else%}mdi:do-not-disturb{%endif%}

#######################################-#######################################
##                                  SENSOR
#######################################-#######################################
sensor:
  - platform: template
    sensors:
      period_of_day:
        entity_id: sensor.time
        value_template: >
          {%set nt=now().time()%}
          {%set nt=(nt.hour*60+nt.minute)*60+nt.second%}
          {%if state_attr('input_datetime.start_morning','timestamp')<=nt<state_attr('input_datetime.start_afternoon','timestamp')%}Mattino
          {%elif state_attr('input_datetime.start_afternoon','timestamp')<=nt<state_attr('input_datetime.start_evening','timestamp')%}Pomeriggio
          {%elif state_attr('input_datetime.start_evening','timestamp')<=nt<state_attr('input_datetime.start_night','timestamp')%}Sera
          {%elif (state_attr('input_datetime.start_evening','timestamp')>state_attr('input_datetime.start_night','timestamp'))
          and (nt>state_attr('input_datetime.start_evening','timestamp') or nt<state_attr('input_datetime.start_night', 'timestamp'))%}Sera
          {%else%}Notte{%endif%}
        icon_template: >
          {%if is_state('sensor.period_of_day','Mattino')%}mdi:weather-sunset-up
          {%elif is_state('sensor.period_of_day','Pomeriggio')%}mdi:weather-sunny
          {%elif is_state('sensor.period_of_day','Sera') %}mdi:weather-sunset-down
          {%else%} mdi:weather-night{%endif%}
      period_of_day_volume:
        entity_id: sensor.time, sensor.period_of_day,input_number.morning_volume,input_number.afternoon_volume,input_number.evening_volume,input_number.night_volume
        value_template: >
          {%if is_state('sensor.period_of_day','Mattino') %}{{states('input_number.morning_volume')|int/100}}
          {%elif is_state('sensor.period_of_day','Pomeriggio')%}{{states('input_number.afternoon_volume')|int/100}}
          {%elif is_state('sensor.period_of_day','Sera') %}{{states('input_number.evening_volume')|int/100}}
          {%else%}{{states('input_number.night_volume')|int/100}}{%endif%}
        icon_template: >
          {%if is_state('sensor.period_of_day_volume','0.0')%}mdi:volume-off
          {%elif is_state('sensor.period_of_day_volume','0.1')%}mdi:volume-low
          {%elif is_state('sensor.period_of_day_volume','0.2')%}mdi:volume-low
          {%elif is_state('sensor.period_of_day_volume','0.3')%}mdi:volume-low
          {%elif is_state('sensor.period_of_day_volume','0.4')%}mdi:volume-medium
          {%elif is_state('sensor.period_of_day_volume','0.5')%}mdi:volume-medium
          {%elif is_state('sensor.period_of_day_volume','0.6')%}mdi:volume-medium
          {%else%}mdi:volume-high{%endif%}

#######################################-#######################################
##                                  SCRIPT
#######################################-#######################################
script:
  #----------------------------------------------------------------------------------------------------#
  # SCRIPT PRINCIPALE - Variabili da passare all'evento HUB + file template se incluso
  #----------------------------------------------------------------------------------------------------#
  my_notify:
    alias: HUB
    sequence:
      - event: hub
        event_data_template:
          # --------------------------------------------- #
          # VARIABILI
          # --------------------------------------------- #
          called_number: >-
            {{called_number}}
          title: >-
            {{title}}
          link: >-
            {{link}}
          volume: >-
            {{volume}}
          mute: >-
            {{mute}}
          no_show: >-
            {{no_show}}
          notify: >-
            {{notify}}
          location: >-
            {{location}}
          url: >-
            {{url}}
          file: >-
            {{file}}
          caption: >-
            {{caption}}
          alexa_type: >-
            {{alexa_type}}
          alexa_method: >-
            {{alexa_method}}
          alexa_push: >-
            {{alexa_push}}
          media_player_google: >-
            {{media_player_google}}
          media_player_alexa: >-
            {{media_player_alexa}}
          language: >-
            {{language}}
          priority: >-
            {{priority}}
          message_tts: >-
            {{message_tts}}
          #-----------------------------------------------------------------------------#
          # FILE DA INCLUDERE PER LE MACRO - NOTA: NON MODIFICARE L'ESTENSIONE .yml
          #-----------------------------------------------------------------------------#
          message: !include hub_build_message.yml

#######################################-#######################################
##                                 AUTOMATION
#######################################-#######################################
automation:
#1-----------------------------------------------------------------------------------------------------#
  # LAST MESSAGE - Ripete l'ultimo messaggio inviato
  #----------------------------------------------------------------------------------------------------#
  - id: notification_repeat_last_message_hub
    alias: notification_repeat_last_message_hub
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_boolean.last_message
        to: 'on'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.priority_message
      - service: script.my_notify
        data:
          call_no_annuncio: 1
          title: "Ultimo messaggio"
        data_template:
          volume: >
            {{states('input_number.intercom_message_volume')|int/100}}
          message: >
            {{states('input_text.last_message')}}
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.last_message
          - input_boolean.priority_message

#2-----------------------------------------------------------------------------------------------------#
  # INTERFONO
  #----------------------------------------------------------------------------------------------------#
  - id: send_intercom_message_hub
    alias: send_intercom_message_hub
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_text.intercom_message_hub
    condition:
      condition: template
      value_template: >
        {{states('input_text.intercom_message_hub')|length>0}}
    action:
      - service: script.my_notify
        data:
          call_no_annuncio: 1
          title: "Interfono"
        data_template:
          volume: >
            {{states('input_number.intercom_message_volume')|int/100}}
          message: >
            {{states('input_text.intercom_message_hub')~' '}}
      - service: input_text.set_value
        data:
          entity_id: input_text.intercom_message_hub
          value: ''
#3-----------------------------------------------------------------------------------------------------#
  # GUEST - Modalità ospite On e Off - Il TTS funziona anche se si è fuori casa.
  #         Utile anche se si volgiono escludere delle automazioni se ci sono ospiti in casa
  #----------------------------------------------------------------------------------------------------#
  - id: guest_mode_hub
    alias: guest_mode_hub
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.guest_mode
    action:
      - service: script.my_notify
        data:
          call_no_annuncio: 1
          call_modo_ospite: 1
        data_template:
          title: >
            Modalità Ospite - {{trigger.to_state.state|upper}}
#4-----------------------------------------------------------------------------------------------------#
  # AUTO GROUP TTS - Crea un Gruppo Notifiche se l'attributo "id:" dell'automazione finisce con "_hub"
  #----------------------------------------------------------------------------------------------------#
  - id: create_notification_automation_group_hub
    alias: create_notification_automation_group_hub
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: automation.create_notification_automation_group_hub
        to: 'on'
    action:
      - delay: 00:00:30
      - service: group.set
        data_template:
          object_id: "automations_notification_hub"
          name: "Automazioni Centro Notifiche"
          visible: true
          entities: >
            {%for item in states.automation if ((item.attributes.id|lower).endswith('hub'))%}
            {{-item.entity_id}}{%if not loop.last%},{%endif-%}{%endfor%}
