binary_sensor:
  - platform: template
    sensors:
      people_home:
        friendly_name: Persone in casa
        device_class: presence
        value_template: "{{is_state('group.location_tracker','home')}}"
        attribute_templates:
          number: >-
            {% if is_state('group.location_tracker','home')%}
            {{expand('group.location_tracker')|selectattr('state','eq','home')
            |list|count+(1 if is_state('input_boolean.guest_mode','on') else 0)}}
            {%endif%}
          name: >-
            {% if is_state('group.location_tracker','home')%}
            {{expand('group.location_tracker')|selectattr('state','eq','home')
            |join(', ',attribute='name')~(', Ospiti' if is_state('input_boolean.guest_mode','on') else '')}}
            {%endif%}
            
