binary_sensor:
  - platform: workday
    country: IT
    workdays: [mon, tue, wed, thu, fri, sat]
    excludes: [sun, holiday]
    add_holidays:
      - "2023-08-31"
      - "2024-08-31"
      - "2025-08-31"
      - "2026-08-31"
      - "2027-08-31"
      - "2028-08-31"
      - "2029-08-31"
      - "2030-08-31"
