sensor:
  - platform: command_line
    name: HA Start
    command: grep -m1 'Home Assistant initialized' home-assistant.log | awk '{ print $6, $7, $8, $9, $10 }'
  ############################################################################
  ## In order to use sensor.ha_start, set the info logs in this way
  ############################################################################
  # logger:
  #   default: warn # or whatever you want (info, error...)
  #   logs:
  #     homeassistant.bootstrap: info

  # Time & Date https://www.home-assistant.io/integrations/time_date/
  - platform: time_date
    display_options:
      # - "beat"
      - "date"
      # - "date_time"
      # - "date_time_iso"
      # - "date_time_utc"
      - "time"
      # - "time_date"
      # - "time_utc"

template:
  - sensor:
        # Calcolo Giorno della settimana # [now().weekday()]
      - name: Day of week
        unique_id: day_of_week
        state: >-
          {{ [
              'lunedì',
              'martedì',
              'mercoledì',
              'giovedì',
              'venerdì',
              'sabato',
              'domenica'
            ][as_datetime(states('sensor.date')).weekday()] }}
        icon: >-
          mdi:{{ [
            'emoticon-dead-outline',
            'emoticon-angry-outline',
            'emoticon-sad-outline',
            'emoticon-neutral-outline',
            'emoticon-cool-outline',
            'emoticon-excited-outline',
            'emoticon-happy-outline'
          ][as_datetime(states('sensor.date')).weekday()] }}

        # Calcolo Giorno dopo
      - name: Tomorrow day of week #Domani
        unique_id: tomorrow_day_of_week
        state: >-
          {{ ['mar','mer','gio','ven','sab','dom','lun'][as_datetime(states('sensor.date')).weekday()] }}
        icon: >-
          mdi:{{ [
            'emoticon-angry-outline', 
            'emoticon-sad-outline',
            'emoticon-neutral-outline',
            'emoticon-cool-outline',
            'emoticon-excited-outline',
            'emoticon-happy-outline',
            'emoticon-dead-outline'
          ][as_datetime(states('sensor.date')).weekday()] }}

      # Ultimo giorno del mese
      - name: "Last Day of the Month"
        unique_id: last_day_of_the_month
        icon: "mdi:calendar"
        state: >-
          {{ as_datetime(states('sensor.date')).day + 1 == 1 }}
