#----------------------------------------------------------------------------------------------------#
# Le entità (entity_id, o friendly_name) vanno inserite come segue ["entità","entià2","ultima entità"]
# L'insieme dell'entità va tra prentesi quadre, e ognuna di esse va all'interno delle virgolette
# separate dalla virgola, eccetto per l'ultima o unica uenità.
#----------------------------------------------------------------------------------------------------#
location_tracker_hub:
  - person.claudio


#----------------------------------------------------------------------------------------------------#
# Inserire i propri dispositivi GOOGLE e/o GROUP con il proprio friandly_name
#----------------------------------------------------------------------------------------------------#
notification_media_player_google_hub: 
  - Red
  - Black
  - Black2
  - Gruppo Casa
  - Gruppo Google
  - Gruppo Google Notte


#----------------------------------------------------------------------------------------------------#
# Inserire i propri dispositivi ALEXA e/o GROUP con il proprio friandly_name.
#----------------------------------------------------------------------------------------------------#
notification_media_player_alexa_hub:
  - Sala
  - Studio
  - Gruppo Alexa
  - Dappertutto
  - Last Alexa

#----------------------------------------------------------------------------------------------------#
# Inserire i propri servizi di notifica   http://hassio:8123/dev-service nel campo servizio           
#                                         digita notify. (con il punto) e vedrai quali sono i tuoi    
#----------------------------------------------------------------------------------------------------#
default_notify_hub: 
  - Telegram
  - TelegramHTML
  - Pushover
  - Android
  - Pushbullet
  - Test Nome NOTIFICA
  - Mobile App Oneplus 5t

#----------------------------------------------------------------------------------------------------#
# APP ARIELA TTS - Inserire MQTT Topic Trigger in ariela_tts
# Dal Menu/Impostazioni/Sensors/Text to Speech - attivare il sensore, selezionare MQTT 
# copiare il codice premendo sui tre puntini veritcali.
# APP ARIELA NOTIFY - PUSH
# Dal Menu/Impostazioni/Notifiche/Mobile APP Notification
# copiare il nome del servizio in ariela_notify
#----------------------------------------------------------------------------------------------------#

secret_ariela_mqtt: homeassistant/tts/android_oneplus_5t_tts/tts
#ariela_tts: homeassistant/tts/android_oneplus_5t_tts/tts
ariela_notify: notify.mobile_app_oneplus_5t
##